/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProjectsPhotosRouteImport } from './routes/_authenticated/projects..photos'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects.new'
import { Route as AuthenticatedProjectsInterviewRouteImport } from './routes/_authenticated/projects..interview'
import { Route as AuthenticatedProjectsGenerateRouteImport } from './routes/_authenticated/projects..generate'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedContentContentIdRouteImport } from './routes/_authenticated/content.$contentId'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects.'
import { Route as AuthenticatedContentRouteImport } from './routes/_authenticated/content.'
import { Route as AuthenticatedProjectsProjectIdPhotosRouteImport } from './routes/_authenticated/projects.$projectId.photos'
import { Route as AuthenticatedProjectsProjectIdInterviewRouteImport } from './routes/_authenticated/projects.$projectId.interview'
import { Route as AuthenticatedProjectsProjectIdGenerateRouteImport } from './routes/_authenticated/projects.$projectId.generate'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsPhotosRoute =
  AuthenticatedProjectsPhotosRouteImport.update({
    id: '/projects/photos',
    path: '/projects/photos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsInterviewRoute =
  AuthenticatedProjectsInterviewRouteImport.update({
    id: '/projects/interview',
    path: '/projects/interview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsGenerateRoute =
  AuthenticatedProjectsGenerateRouteImport.update({
    id: '/projects/generate',
    path: '/projects/generate',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentContentIdRoute =
  AuthenticatedContentContentIdRouteImport.update({
    id: '/content/$contentId',
    path: '/content/$contentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContentRoute = AuthenticatedContentRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsProjectIdPhotosRoute =
  AuthenticatedProjectsProjectIdPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdInterviewRoute =
  AuthenticatedProjectsProjectIdInterviewRouteImport.update({
    id: '/interview',
    path: '/interview',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdGenerateRoute =
  AuthenticatedProjectsProjectIdGenerateRouteImport.update({
    id: '/generate',
    path: '/generate',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/content/': typeof AuthenticatedContentRoute
  '/projects/': typeof AuthenticatedProjectsRoute
  '/content/$contentId': typeof AuthenticatedContentContentIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/generate': typeof AuthenticatedProjectsGenerateRoute
  '/projects/interview': typeof AuthenticatedProjectsInterviewRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/projects/photos': typeof AuthenticatedProjectsPhotosRoute
  '/projects/$projectId/generate': typeof AuthenticatedProjectsProjectIdGenerateRoute
  '/projects/$projectId/interview': typeof AuthenticatedProjectsProjectIdInterviewRoute
  '/projects/$projectId/photos': typeof AuthenticatedProjectsProjectIdPhotosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/content': typeof AuthenticatedContentRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/content/$contentId': typeof AuthenticatedContentContentIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/generate': typeof AuthenticatedProjectsGenerateRoute
  '/projects/interview': typeof AuthenticatedProjectsInterviewRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/projects/photos': typeof AuthenticatedProjectsPhotosRoute
  '/projects/$projectId/generate': typeof AuthenticatedProjectsProjectIdGenerateRoute
  '/projects/$projectId/interview': typeof AuthenticatedProjectsProjectIdInterviewRoute
  '/projects/$projectId/photos': typeof AuthenticatedProjectsProjectIdPhotosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/content/': typeof AuthenticatedContentRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsRoute
  '/_authenticated/content/$contentId': typeof AuthenticatedContentContentIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/projects/generate': typeof AuthenticatedProjectsGenerateRoute
  '/_authenticated/projects/interview': typeof AuthenticatedProjectsInterviewRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/projects/photos': typeof AuthenticatedProjectsPhotosRoute
  '/_authenticated/projects/$projectId/generate': typeof AuthenticatedProjectsProjectIdGenerateRoute
  '/_authenticated/projects/$projectId/interview': typeof AuthenticatedProjectsProjectIdInterviewRoute
  '/_authenticated/projects/$projectId/photos': typeof AuthenticatedProjectsProjectIdPhotosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/library'
    | '/onboarding'
    | '/settings'
    | '/content/'
    | '/projects/'
    | '/content/$contentId'
    | '/projects/$projectId'
    | '/projects/generate'
    | '/projects/interview'
    | '/projects/new'
    | '/projects/photos'
    | '/projects/$projectId/generate'
    | '/projects/$projectId/interview'
    | '/projects/$projectId/photos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/library'
    | '/onboarding'
    | '/settings'
    | '/content'
    | '/projects'
    | '/content/$contentId'
    | '/projects/$projectId'
    | '/projects/generate'
    | '/projects/interview'
    | '/projects/new'
    | '/projects/photos'
    | '/projects/$projectId/generate'
    | '/projects/$projectId/interview'
    | '/projects/$projectId/photos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/library'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/content/'
    | '/_authenticated/projects/'
    | '/_authenticated/content/$contentId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/generate'
    | '/_authenticated/projects/interview'
    | '/_authenticated/projects/new'
    | '/_authenticated/projects/photos'
    | '/_authenticated/projects/$projectId/generate'
    | '/_authenticated/projects/$projectId/interview'
    | '/_authenticated/projects/$projectId/photos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/photos': {
      id: '/_authenticated/projects/photos'
      path: '/projects/photos'
      fullPath: '/projects/photos'
      preLoaderRoute: typeof AuthenticatedProjectsPhotosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/interview': {
      id: '/_authenticated/projects/interview'
      path: '/projects/interview'
      fullPath: '/projects/interview'
      preLoaderRoute: typeof AuthenticatedProjectsInterviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/generate': {
      id: '/_authenticated/projects/generate'
      path: '/projects/generate'
      fullPath: '/projects/generate'
      preLoaderRoute: typeof AuthenticatedProjectsGenerateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/$contentId': {
      id: '/_authenticated/content/$contentId'
      path: '/content/$contentId'
      fullPath: '/content/$contentId'
      preLoaderRoute: typeof AuthenticatedContentContentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content/': {
      id: '/_authenticated/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof AuthenticatedContentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/photos': {
      id: '/_authenticated/projects/$projectId/photos'
      path: '/photos'
      fullPath: '/projects/$projectId/photos'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPhotosRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/interview': {
      id: '/_authenticated/projects/$projectId/interview'
      path: '/interview'
      fullPath: '/projects/$projectId/interview'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdInterviewRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/generate': {
      id: '/_authenticated/projects/$projectId/generate'
      path: '/generate'
      fullPath: '/projects/$projectId/generate'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdGenerateRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdGenerateRoute: typeof AuthenticatedProjectsProjectIdGenerateRoute
  AuthenticatedProjectsProjectIdInterviewRoute: typeof AuthenticatedProjectsProjectIdInterviewRoute
  AuthenticatedProjectsProjectIdPhotosRoute: typeof AuthenticatedProjectsProjectIdPhotosRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdGenerateRoute:
      AuthenticatedProjectsProjectIdGenerateRoute,
    AuthenticatedProjectsProjectIdInterviewRoute:
      AuthenticatedProjectsProjectIdInterviewRoute,
    AuthenticatedProjectsProjectIdPhotosRoute:
      AuthenticatedProjectsProjectIdPhotosRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedContentRoute: typeof AuthenticatedContentRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedContentContentIdRoute: typeof AuthenticatedContentContentIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedProjectsGenerateRoute: typeof AuthenticatedProjectsGenerateRoute
  AuthenticatedProjectsInterviewRoute: typeof AuthenticatedProjectsInterviewRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedProjectsPhotosRoute: typeof AuthenticatedProjectsPhotosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedContentRoute: AuthenticatedContentRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedContentContentIdRoute: AuthenticatedContentContentIdRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedProjectsGenerateRoute: AuthenticatedProjectsGenerateRoute,
  AuthenticatedProjectsInterviewRoute: AuthenticatedProjectsInterviewRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedProjectsPhotosRoute: AuthenticatedProjectsPhotosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
